### ISSUE TITLE
Coding standards compliance in 3.x branch

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#36] opened 2014-04-07 21:33 UTC
Code sniffer analysis reveals 268 issues, most of which are valid.

Especially given the nature of this project, the code needs to be perfect, within reason.

The PHP Code Sniffer code inspector in PHPStorm is your friend.

**Comment by unclegcb** [comment] 2014-04-08 15:27
well, looks like codesniffer stopped running when I upgraded to phpstorm 7! Hey @ruscoe, wanna try getting Codesniffer setup and digging through the Campaign and Activity module code with it turned on?

http://tiger-fish.com/blog/writing-better-drupal-7-code-phpstorm-and-codesniffer

I've run the manual inspection through the coder module and cleaned up the rest of the module.

**Comment by ruscoe** [comment] 2014-04-08 16:07
@unclegcb I'd be happy to. I'll take care of it today.

**Comment by ruscoe** [comment] 2014-04-10 18:36
Changes committed to 7.x-3.x.

I ignored some type compatibility issues that were caused by the MailChimp API using "@ param associative_array" instead of "@ param array" because "associative_array" is not standard in PHPDoc.

**Closed as completed by ruscoe** 2014-04-10 18:36 UTC
